# Generated by Django 5.2.9 on 2025-12-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="route",
            unique_together={("source", "destination")},
        ),
    ]
