# Generated by Django 5.2.9 on 2025-12-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0002_alter_route_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="route",
            unique_together=set(),
        ),
    ]
