# Generated by Django 5.2.9 on 2025-12-29 13:54

import station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0003_alter_route_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="image",
            field=models.ImageField(
                null=True, upload_to=station.models.station_image_path
            ),
        ),
    ]
